jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: |
          cd NarrativaX  # Peka på mappen där package.json finns
          npm install
      - name: Build the app
        run: |
          cd NarrativaX  # Peka på mappen där package.json finns
          npm run build
      - name: Deploy to production
        run: |
          cd NarrativaX  # Peka på mappen där package.json finns
          npm run deploy
